name: lifelog
description: A simple life logging app to track moments with time, mood, and events
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
